name: Deploy to Azure Kubernetes Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure 로그인
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure AKS context 설정
        uses: azure/aks-set-context@v3
        with:
          resource-group: aks-rg
          cluster-name: aks-cluster

      - name: Helm 설치
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Helm chart 배포
        run: |
          helm upgrade --install flask-nginx ./flask-nginx-chart
