jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push changes
        run: |
          git config user.email "cloudyshin1@gmail.com"
          git config user.name "Miogun"
          git remote set-url origin git@github.com:Miogun/docker_kubernetes.git
          git push origin main

